---
  - name: Remove Enterprise Repos
    file:
      path: /etc/apt/sources.list.d/pve-enterprise.list
      state: absent

  - name: Remove Enterprise Repos
    file:
      path: /etc/apt/sources.list.d/pve-enterprise.list.dpkg-dist
      state: absent

  - name: Add No Subscription Repository
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
      state: present

  - name: Tag - Update (Update Everything)
    ansible.builtin.import_tasks:
      file: tag_update.yml

  - name: Install required packages
    ansible.builtin.apt:
      name: sudo
      state: latest

